---
title: "Run CIFAR10"
author: "Jesse Leigh Patsolic"
output: 
  html_document:
    keep_md: true
    toc: true
    code_folding: show
    self_contained: true
---

<!--
### ### INITIAL COMMENTS HERE ###
###
### Jesse Leigh Patsolic 
### 2018 <jpatsolic@jhu.edu>
### S.D.G 
#
-->

```{r render-code, eval=FALSE, echo=FALSE}
rm(list = ls())
seedJ <- 317
set.seed(seedJ)

require(slackr)                       
slackrSetup(config_file = '~/neurodata-slackr.conf')

require(rmarkdown)
require(knitr); knitr::opts_chunk$set(cache=FALSE, autodep=TRUE, eval = TRUE)

msg0 <- paste("Synaptomes1 has started running cifar10 at", Sys.time())
slackr_msg(msg0)

rmarkdown::render("runCIFAR10.Rmd")
```

<style type="text/css">
.table {
    width: 40%;
}
tr:hover {background-color:#f5f5f5;}
</style>

```{r setup}
seedJ <- 317
require(rmarkdown)
require(knitr)
require(devtools)
require(raster)
require(ggplot2)
require(MCMCpack)
require(data.table)
require(gridExtra)

require(devtools)
if(version$os == "linux-gnu"){
  devtools::install_github("neurodata/r-rerf", ref = "jlp-gaborFilter01")
}
require(rerf)

print("loading data ...")

load("~/data/cifar10.RData")

fi <- file("R-RerF-jlp-gaborFilter01/R/RandMat.R", "r")
source(textConnection(readLines(fi)[674:838])) # Source only the new RandMatGabor function
close(fi); rm(fi)
```


# CIFAR10

```{r getCIFAR}
names(cifar10)
(u <- sort(unique(cifar10$Ytrain)))

Batch <- cifar10$Batch
ind <- 1:length(Batch) #sample(which(Batch == 1), 500L)

X <- cifar10$Xtrain[ind, ]
Xtrain <- cifar10$XtrainGray[ind,]
Xtest <- cifar10$XtestGray

Ytrain <- cifar10$Ytrain[ind]
Ytest <- cifar10$Ytest
```

## Look At It color and gray-scale

```{r lai1, fig.height = 8, fig.width = 8}
set.seed(seedJ)
par(bg=NA,mar=c(0,0,0,0),oma=c(0,0,0,0))
par(mfrow = c(3,3))

for(i in sample(nrow(X), 9)){
  im <- aperm(array(X[i, ], dim = c(32, 32, 3)), perm = c(2,1,3))
  plot(as.raster(im, max = 255))
}
```

```{r p2, fig.height = 8, fig.width = 8}
set.seed(seedJ)
par(bg=NA,mar=c(0,0,0,0),oma=c(0,0,0,0))
par(mfrow = c(3,3))

for(i in sample(nrow(Xtrain), 9)){
  im <- aperm(array(Xtrain[i, ], dim = c(32, 32)))
  plot(as.raster(im))
}
```


# Start R-RerF run
```{r, echo = FALSE, results = 'asis'}
ntrees <- 500L
seed1 <- 1L
ncores <- 48L

p <- 32^2
d <- 40
iw <- 32
ih <- 32
patch.min <- 1
patch.max <- 15
sparsity <- 0.1
tol <- 10^8 * 
  .Machine$double.eps

kable(as.data.frame((params <- list(p = p, d = d, iw = iw, ih = ih, pwMin = patch.min, pwMax = patch.max, sparsity = sparsity, tol = tol))), digits = 8)
```

### RerF-Continuous

```{r rerf-continuous}
system.time({
forestC <- RerF(Xtrain, as.factor(Ytrain),  FUN = RandMatContinuous, 
               paramList = params,
               trees = ntrees, store.oob = TRUE,
               num.cores = ncores, seed = seed1)
})

predC <- Predict(Xtest, forestC, num.cores = ncores)
oobC <- OOBPredict(Xtrain, forestC, num.cores = ncores)
(ooberC <- mean(oobC != Ytrain))
(errorC <- mean(predC != Ytest))
```

#### Plots of errors

```{r pC, eval = FALSE}
errIND <- which(predC != Ytest)

par(bg=NA,mar=c(0,0,0,0),oma=c(0,0,0,0))
par(mfrow = c(ceiling(length(errIND)/3),3))

for(i in errIND) {
  im <- aperm(array(Xtrain[i, ], dim = c(32, 32)))
  plot(as.raster(im, max = 1))
}
```


```{r rerf-gabor}
system.time({
forestG <- RerF(Xtrain, as.numeric(as.factor(Ytrain)),  FUN = RandMatGabor, 
               paramList = params,
               trees = ntrees, store.oob = TRUE,
               num.cores = ncores, seed = seed1)
})

predG <- Predict(Xtest, forestG, num.cores = ncores)
oobG <- OOBPredict(Xtrain, forestG, num.cores = ncores)
(ooberG <- mean(oobG != Ytrain))
(errorG <- mean(predG != as.numeric(as.factor(Ytest))))
```

#### Plots of errors

```{r pg, eval = FALSE}
errIND <- which(predG != as.numeric(as.factor(Ytest)))

par(bg=NA,mar=c(0,0,0,0),oma=c(0,0,0,0))
par(mfrow = c(ceiling(length(errIND)/3),3))
for(i in errIND) {
  im <- aperm(array(Xtrain[i, ], dim = c(32, 32)))
  plot(as.raster(im, max = 1))
}
```

### RerF-image-patch

```{r rerf-image-patch}
system.time({
forestIp <- RerF(Xtrain, as.numeric(as.factor(Ytrain)),  FUN = RandMatImagePatch, 
               paramList = params,
               trees = ntrees, store.oob = TRUE,
               num.cores = ncores, seed = seed1)
})

predIp <- Predict(Xtest, forestIp, num.cores = ncores)
oobIp <- OOBPredict(Xtrain, forestIp, num.cores = ncores)
(ooberIp <- mean(oobIp != Ytrain))
(errorIp <- mean(predIp != as.numeric(as.factor(Ytest))))
```

#### Plots of errors

```{r pip, eval = FALSE}
errIND <- which(predIp != as.numeric(as.factor(Ytest)))

par(bg=NA,mar=c(0,0,0,0),oma=c(0,0,0,0))
par(mfrow = c(ceiling(length(errIND)/3),3))
for(i in errIND) {
  im <- aperm(array(Xtrain[i, ], dim = c(32, 32)))
  plot(as.raster(im, max = 1))
}
```



```{r notify, echo = FALSE}
msg <- 
  paste("Synaptomes1 has finished the run at", Sys.time())
slackr_msg(msg)
save.image(file = paste0("syn1_cifar10", format(Sys.time(), "%Y%m%dT%H%M%S"), ".RData"))
```

<!--
#   Time:
##  Working status:
### Comments:
####Soli Deo Gloria
--> 

